# pretrain settings
dims:
  type: list_int
  default:
    - 500
    - 500
    - 2000
    - 10
  help: "The dimension of auto encoder."

pretrain_path:
  type: str
  default: "./model_saves/MNIST/DEC/pretrain/ckpt_100000.pt"
  help: "The path to store the pretrain model."

method_name:
  type: str
  default: "DEC"
  help: "The method name."
